# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle
oneup_flysystem:
    adapters:
        public_adapter:
            local:
                location: '%kernel.project_dir%/public/uploads'
        private_adapter:
            local:
                location: '%kernel.project_dir%/var/private'
    filesystems:
        public_filesystem:
            adapter: public_adapter
        private_filesystem:
            adapter: private_adapter
